---
# Name your file secrets.yml

development:
  # Infrastructure 
  DB_FILENAME: db/local/dev.db
  INSTAGRAM_TOKEN: create_instagram_api_token
  ACCOUNT_ID: create_instagram_account_id
  # Application
  APP_HOST: http://localhost:9000
  SESSION_SECRET: <some secret>

app_test:
  # Infrastructure
  DB_FILENAME:    app/infrastructure/database/local/test.db
  # Application
  APP_HOST: http://localhost:9000

test:
  # Infrastructure 
  DB_FILENAME: db/local/test.db
  INSTAGRAM_TOKEN: create_instagram_api_token
  ACCOUNT_ID: create_instagram_account_id
  # Application
  APP_HOST: http://localhost:9000
  SESSION_SECRET: <some secret>

production:
  # Infrastructure
  # - assign DATABASE_URL in production
  INSTAGRAM_TOKEN: create_instagram_api_token
  ACCOUNT_ID: create_instagram_account_id
  # Application
  APP_HOST: http://url.to.app
  SESSION_SECRET: <some secret>